# Configurazione principale di BossCore
# Plugin creato da Fl1uxxNoob

# Impostazioni generali
settings:
  debug-mode: false
  prefix: "&8[&c&lBoss&f&lCore&8] &r"

# Impostazioni dell'evento
event:
  # Durata del countdown in secondi
  countdown: 15

  # Visibilità del boss durante il countdown (se true, il boss sarà visibile ma non attaccabile)
  visible-during-countdown: false

  # Posizione di spawn del boss
  location:
    world: "world"
    x: 0
    y: 64
    z: 0

  # Impostazioni del boss
  boss:
    # Numero di hit necessarie per uccidere il boss
    health: 100
    # Nome personalizzato del boss
    name: "&c&lBoss &f&lEvent"
    # Formato del display del nome (con vita)
    display-format: "&c&l%name% &7| &eVita: &a%health%"

abilities:
  # Raggio massimo per il rilevamento dei giocatori per le abilità
  max-detection-range: 20.0

  # Abilità di respingimento
  pushback:
    # Se l'abilità è abilitata o no
    enabled: true
    # Numero di colpi dopo i quali il boss attiva l'abilità
    trigger-hits: 10
    # Raggio d'azione dell'abilità (in blocchi)
    range: 5.0
    # Potenza di respingimento orizzontale
    power-horizontal: 2.0
    # Potenza di respingimento verticale
    power-vertical: 0.5
    # Suono da riprodurre quando l'abilità viene attivata
    sound: "EXPLODE"
    # Messaggio da visualizzare quando l'abilità viene attivata
    message: "&c&lIl boss respinge tutti i giocatori!"

# Configurazione delle scoreboard
scoreboard:
  # Configurazione della scoreboard del countdown
  countdown:
    enabled: true
    title: "&c&lBoss&f&lEvent"
    lines:
      - "&7"
      - "&eEvento inizia in: &a%time%s"
      - "&7"
      - "&fPrimo: &6%reward1%"
      - "&fSecondo: &6%reward2%"
      - "&fTerzo: &6%reward3%"
      - "&7"
      - "&fServer: &e%server%"

  # Configurazione della scoreboard dell'evento
  event:
    enabled: true
    title: "&c&lBoss&f&lEvent"
    lines:
      - "&eVita Boss: &a%health%"
      - "&fPosizione: &e%boss_x%, %boss_y%, %boss_z% &7(%boss_world%)"
      - "&7"
      - "&aI tuoi colpi: &e%yourhits%"
      - "&7"
      - "&6TOP GIOCATORI:"
      - "&f#1: %player1% &7- &e%hits1%"
      - "&f#2: %player2% &7- &e%hits2%"
      - "&f#3: %player3% &7- &e%hits3%"
      - "&7"
      - "&fServer: &e%server%"

# Premi per i vincitori (comandi eseguiti come console)
rewards:
  # Primo posto
  rank1: "give %player% diamond_block 3"
  # Secondo posto
  rank2: "give %player% diamond_block 2"
  # Terzo posto
  rank3: "give %player% diamond_block 1"
  # Descrizioni dei premi (usati nella scoreboard)
  desc:
    rank1: "3x Diamond Block"
    rank2: "2x Diamond Block"
    rank3: "1x Diamond Block"

# Messaggi del plugin
messages:
  reload: "&aConfigurazione ricaricata con successo!"
  no-permission: "&cNon hai il permesso per eseguire questo comando!"
  player-only: "&cQuesto comando può essere eseguito solo da un giocatore!"
  location-set: "&aLa posizione di spawn del boss è stata impostata con successo!"

  commands:
    help: |
      &8&m----------------------------------------
      &c&lBoss&f&lCore &7- &fComandi disponibili:
      &8» &f/bosscore start &7- Avvia l'evento del boss
      &8» &f/bosscore stop &7- Ferma l'evento del boss
      &8» &f/bosscore reload &7- Ricarica la configurazione
      &8» &f/bosscore setlocation &7- Imposta la posizione di spawn
      &8» &f/bosscore credits &7- Mostra i crediti del plugin
      &8&m----------------------------------------

  event:
    starting: "&aAvvio del countdown per l'evento del boss!"
    countdown-started: "&aPrepararsi! L'evento del boss inizierà tra &e%time% &asecondi!"
    countdown: "&aL'evento del boss inizierà tra &e%time% &asecondi!"
    started: "&a&lL'evento del boss è iniziato! Colpisci il boss più volte per vincere!"
    ended: "&c&lL'evento del boss è terminato!"
    stopped: "&cL'evento del boss è stato interrotto manualmente."
    countdown-stopped: "&cIl countdown è stato interrotto manualmente."
    countdown-cancelled: "&cIl countdown per l'evento del boss è stato annullato."
    already-running: "&cL'evento del boss è già in corso!"
    already-starting: "&cIl countdown per l'evento del boss è già in corso!"
    not-running: "&cNessun evento del boss in corso!"
    winner: "&a&lIl vincitore dell'evento è &e%player% &a&lcon &e%hits% &a&lcolpi!"
    no-players: "&c&lL'evento è stato terminato perché non ci sono più giocatori online!"
    ranking: |
      &8&m----------------------------------------
      &c&lBoss&f&lEvent &7- &fClassifica Finale:
      &f#1: %player1% &7- &e%hits1% colpi
      &f#2: %player2% &7- &e%hits2% colpi
      &f#3: %player3% &7- &e%hits3% colpi
      &8&m----------------------------------------

  rewards:
    received: "&aHai ricevuto il premio per esserti classificato &e#%rank%&a!"