name: BossCore
version: 1.5.2
main: net.fliuxx.bossCore.BossCore
api-version: 1.8
author: Fl1uxxNoob
description: Vince chi colpisce più volte il boss!
commands:
  bosscore:
    description: Comando principale di BossCore
    usage: /<command> [start|stop|setlocation|reload|help]
permissions:
  bosscore.admin:
    description: Permette di utilizzare tutti i comandi di BossCore
    default: op